FROM python:3.12-slim

ARG USERNAME=immich-tiktok-remover
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ARG OUTPUT_ALL=False
ARG ARCHIVE=False
ARG SEARCH_ARCHIVED=False
ARG FILE_TYPES=mp4
ARG FILE_NAME_LENGTH=32
ARG FILE_NAME_IS_NOT_ALUMN=False
ARG FILE_CREATED_AFTER=1472688000
ARG TEXT_TO_CHECK=TikTok
ARG AVOID_IMAGE_RECOGNITION=False

ENV OUTPUT_ALL=$OUTPUT_ALL
ENV ARCHIVE=$ARCHIVE
ENV SEARCH_ARCHIVED=$SEARCH_ARCHIVED
ENV FILE_TYPES=$FILE_TYPES
ENV FILE_NAME_LENGTH=$FILE_NAME_LENGTH
ENV FILE_NAME_IS_NOT_ALUMN=$FILE_NAME_IS_NOT_ALUMN
ENV FILE_CREATED_AFTER=$FILE_CREATED_AFTER
ENV TEXT_TO_CHECK=$TEXT_TO_CHECK
ENV AVOID_IMAGE_RECOGNITION=$AVOID_IMAGE_RECOGNITION

# Create the immich-tiktok-remover user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

USER $USERNAME

WORKDIR /home/immich-tiktok-remover

RUN mkdir /home/immich-tiktok-remover/.local

ENV PIP_NO_CACHE_DIR=off 

COPY src/ .
COPY requirements.txt .
COPY run_docker.sh .

RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["./run_docker.sh"]

